
# This file was generated by 'versioneer.py' (0.15) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json
import sys

version_json = '''
{
 "dirty": false,
 "error": null,
 "full-revisionid": "7d3ede29b362d2ae777752c41b9ade8fe05ac32e",
 "version": "1.12.5"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
